config/routes.rb
Rails.application.routes.draw do

  
	root "pages#home"
  	resources :pages
	
	resources :users
	
		resources :universes do
			resources :stories
			resources :days
			resources :events do
				get 'place', on: :member
				resources :places
				end
			resources :chapters
			resources :scenes
			resources :societies
			resources :characters
			resources :artefacts
			resources :places do
				resources :events 
				get 'event', on: :member
				end
			resources :comments
		end
	

	

	
	mount SubdivisionSelect::Engine, at: 'subdivisions'
	
	

  
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

	
	  
	  
	  # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/artefact.rb
class Artefact < ActiveRecord::Base
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_and_belongs_to_many :events, through: :calendars_events
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
end

app/models/character.rb
class Character < ActiveRecord::Base

  has_and_belongs_to_many :relationships
  has_many :participations
  has_many :memberships
	
	
	
	
	belongs_to :univers
  default_scope -> { order(created_at: :desc) }
  validates :univers_id, presence: true
	validates :first_name, presence: true, length: { maximum: 140 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/day.rb
class Day < ActiveRecord::Base
	before_save :set_human_day
	belongs_to :univers
	has_many :events
	accepts_nested_attributes_for :events
	validates_uniqueness_of :date,  scope: :univers_id
	validates :date, presence: true
	validates :human_day, presence: true
	
	def set_human_day
	
	end
	
	
	
end

app/models/event.rb
class Event < ActiveRecord::Base	
  belongs_to :univers
  default_scope -> { order(created_at: :desc) }
  validates :univers_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
	
	belongs_to :day
	accepts_nested_attributes_for :day
#	validates_presence_of :day
	belongs_to :place
	accepts_nested_attributes_for :place
	validates_presence_of :place
	
	validates_uniqueness_of :name, scope: :univers_id
	
	
	
	
	
	
	 has_many :participations
  has_and_belongs_to_many :scenes

	#virtual attribute
#	def place_name
#		place.name if place
#	end
#	
#	def place_name=(name)
#		self.place = Place.find_or_create_by_name(name) || name.blank
#		@place_name.create_by_name(name)
#	end
	

	


	

end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :participation
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :character
  belongs_to :society
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :univers
	default_scope -> { order(created_at: :desc) }
	validates :univers_id, presence: true
	validates :name, presence: true, length: { maximum: 140 }
	
	has_many :events
	accepts_nested_attributes_for :events
	
	validates_uniqueness_of :name, scope: :univers_id
	
		#for the text_method in forms
		def place_city_country
				"#{name} in #{city}, #{country}"
  		end
	
	def country_name
		if ISO3166::Country[country]
		the_country = ISO3166::Country[country]
		the_country.translations[I18n.locale.to_s] || country.name
		end
  	end
	
	
	
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  has_and_belongs_to_many :characters
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  has_and_belongs_to_many :events
  has_many :scene_orders
  has_and_belongs_to_many :stories
end

app/models/scene_order.rb
class SceneOrder < ActiveRecord::Base
  belongs_to :story
  belongs_to :scene
end

app/models/society.rb
class Society < ActiveRecord::Base
  has_many :memberships
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :scene_orders


  #univers
  belongs_to :univers
  default_scope -> { order(created_at: :desc) }
  validates :univers_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }

end

app/models/univers.rb
class Univers < ActiveRecord::Base
	before_save :new_primary
	
	
	
	#User -> Universes
	belongs_to :user
	default_scope -> { order(created_at: :desc) }
	validates :user_id, presence: true
	validates :name, presence: true, length: { maximum: 140 }

	##Univers -> Stories
	has_many :stories, dependent: :destroy

	#Univers -> Events
	has_many :events, dependent: :destroy
	
	#Univers -> Characters
	has_many :characters, dependent: :destroy
	
	#Univers -> Places
	has_many :places, dependent: :destroy
	
	#Univers -> Places
	has_many :chapters, dependent: :destroy
	
	#Univers -> Places
	has_many :days, dependent: :destroy
	
	
	 


	
	def new_primary #falsifies old primary univers as fasle
		Univers.where(user_id: self.user_id).where.not(id: self.id).update_all(:primary => 'false')
	end
	
	
	



end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :universes, dependent: :destroy











### AUTO ------------------------------------------------------
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    
	  <div class="navbar-brand">
	  
		  <b> <%= link_to "Cosmolog", root_path %></b>  <%if @univers %>: <%= 
link_to @univers.name.upcase , univers_path(@univers.id)%><% end%>
	  </div>
	
	
	</div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
		
		<% if @univers %>
		<% if @univers.id  %>
	
		 
			 
            <ul class="nav navbar-nav navbar-left">
				<li><%= link_to "Stories" + " (" + @univers.stories.count.to_s + ")", univers_stories_path(@univers.id) %></li>
				<li><%= link_to "Events" + " (" + @univers.events.count.to_s + ")", univers_events_path(@univers.id) %></li>
				<li><%= link_to "Characters" + " (" + @univers.characters.count.to_s + ")", univers_characters_path(@univers.id) %></li>
				<li class="place_counter"><%= link_to "Places" + " (" + @univers.places.count.to_s + ")", univers_places_path(@univers.id) %></li>
				
              
            </ul>
          <% end%>
		<% end%>
		
		
		
          <li class="dropdown">
			  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username%> <b class="caret"></b></a>
            <ul class="dropdown-menu">
				<li> <%= link_to "my universes", universes_path %> </li>
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>