config/routes.rb
Rails.application.routes.draw do

  
	root "pages#home"
  	resources :pages
	
	resources :users
	
		resources :universes do
			resources :stories
			resources :days
			resources :events do
				get 'place', on: :member
				resources :places
				end
			resources :chapters
			resources :scenes
			resources :societies
			resources :characters
			resources :artefacts
			resources :places do
				resources :events 
				get 'event', on: :member
				end
			resources :comments
		end
	

	

	
	mount SubdivisionSelect::Engine, at: 'subdivisions'
	
	

  
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/event.rb
class Event < ActiveRecord::Base	
  belongs_to :univers
  default_scope -> { order(created_at: :desc) }
  validates :univers_id, presence: true
  validates :name, presence: true, length: { maximum: 140 }
	
	belongs_to :day
	accepts_nested_attributes_for :day
#	validates_presence_of :day
	belongs_to :place
	accepts_nested_attributes_for :place
	validates_presence_of :place
	
	validates_uniqueness_of :name, scope: :univers_id
	
	
	
	
	
	
	 has_many :participations
  has_and_belongs_to_many :scenes

	#virtual attribute
#	def place_name
#		place.name if place
#	end
#	
#	def place_name=(name)
#		self.place = Place.find_or_create_by_name(name) || name.blank
#		@place_name.create_by_name(name)
#	end
	

	


	

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_user_signed_in, only: [:index,:show, :create, :destroy]
	before_action :set_event, only: [:show, :edit, :update, :destroy]
	before_action :set_univers
	before_action :correct_user
	before_action :pull_countries, only: [:edit, :new]
	
	
		respond_to :html, :js, :xml, :json

  # GET /events
  # GET /events.json
  def index
	  @events = @univers.events
	  
	  #FOR SORTING
	  @newarray = Array.new
	  @country_name_array = Array.new
		
	    @events.each do |event|
		  @newarray << event.place.country
		  @country_name_array << event.place.country_name		
		end
	  
		@top_countries =  @newarray.uniq
		@top_countries_name = @country_name_array.uniq
	    @super_countries = Array.new
		
	  
	  
	  
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
	  
	  
	  
	  #get univers_id
	  #get place_id
	  #get new event
	  
#	  @place = @univers.places.build
#	  @event = @place.events.build
	  
	  
	  @days = @univers.days.all
	   
	  @places = @univers.places.all 
	  
	  @event = @univers.events.build

	  
  end

  # GET /events/1/edit
  def edit
	  @places = @univers.places.all
	  @days = @univers.days.all
  end

  # POST /events
  # POST /events.json
  def create
	  
	  
	  @event = @univers.events.build(event_params)

	  respond_to do |format|
		if @event.save
		  format.html { redirect_to univers_events_path, notice: 'Event was successfully created.' }
format.js
			format.json { render :show, status: :created, location: [@univers, @event] }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
	 end  
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
		  format.html { redirect_to univers_events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: [@univers, @event] }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
		format.html { redirect_to univers_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
		params.require(:event).permit(:name, :place_id, :day_id)
    end
	
	
	def place_params
		params.require(:place).permit(:name)
	end

	
	
	
	
	
	def set_univers
		@univers = Univers.find(params[:univers_id])
    end
	
	# Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to root_path
      end
    end
	
	
	
	#check if current user is the creator of the univers
	def correct_user
		unless current_user == @univers.user
			flash[:danger] = "You have no power there"
			redirect_to universes_path
      end
    end
	
		def pull_countries #pull used country in specific univers
		@newarray = Array.new
		@cities = Array.new
		@country_name_array = Array.new
		places = @univers.places.all
		places.each do |place|
			@newarray << place.country
			@country_name_array << place.country_name
			@cities << place.city 
		end
	
		
		@top_countries =  @newarray.uniq
		@top_countries_name = @country_name_array.uniq
		@cities = @cities.compact.uniq
	end
	

	
	
	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_day_field.html.erb
<div class="field" id="day_form">
<%= collection_select(:event, :day_id, @days,
	:id, :human_day, {selected: @days.first},
	{multiple: false, class: "select2", id:"day_field", style:"width: 100%"}) %>
</div>

app/views/events/_event.html.erb
<div class="card col3 <%= event.place.country %> <%= event.day.date%>",  id:"event_<%=event.id%>">
<%= event.name%> | <%= event.day.human_day%><br/>
	in <%= event.place.name%><br/>
	
</div>

app/views/events/_form.html.erb
<%= form_for [@univers, @event], :html => { :class => 'form-horizontal form-model', id: 'new_event_form' }, remote: true do |f| %>
  

<div id="placefield">
	<%= render 'place_fields'%> 
</div>

<%= link_to 'New Place', new_univers_place_path,id: 'new_place_link', remote: true%>



<div class="dayfield">
	<%= render 'day_field'%>
	</div>

<%= link_to 'New Day', new_univers_day_path,id: 'new_day_link', remote: true%>



<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %><br />
</div>



<div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'vex-dialog-button-primary vex-dialog-button vex-first' %>
		
		<%= link_to 'cancel', '#', :class => 'vex-dialog-button-secondary vex-dialog-button vex-last' %>
    </div>
  </div>


<% end %>

app/views/events/_place_fields.html.erb
<div class="field" id="place_form">
<%= collection_select(:event, :place_id, @places,
	:id, :name, {selected: @places.last},
	{multiple: false, class: 'select2', id: 'place_field', style:"width: 100%"}) %>
  </div>

app/views/events/create.js.erb
vex.close();
$('#event-grid').prepend('<%= j render(@event)%>').isotope( 'reloadItems' ).isotope({ sortBy: 'original-order' });

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Event %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<div class="filters_nav">
	<%= link_to "New Place", new_univers_event_path, id: 'new_place_link', remote: true %> <br/>



	
filtering years
<div class="button-group filters-button-group">
	 <button class="button is-checked" data-filter="*">show all</button>
	<% @events.each do |event| %>
	
	
	<% if event.nil?%>
	
	<button class="button" data-filter=".nocountry"> no country</button>
	
	<%else%>
	<button class="button" data-filter=".<%= event.day.date%>"> <%= event.day.date%></button>
	<%end%>
	
	
<%end%>
</div>
	
	
	
	filtering Countries
<div class="button-group filters-button-group">
	 <button class="button is-checked" data-filter="*">show all</button>
	<% @top_countries.each do |country| %>
	
	
	<% if country.nil?%>
	
	<button class="button" data-filter=".nocountry"> no country</button>
	
	<%else%>
	<button class="button" data-filter=".<%= country%>"> <%= country %></button>
	<%end%>
	
	
<%end%>
</div>
	
	
	
	
	
	
	
Sorting Countries

 <div class="button-group sort-place-by-button-group">
  <button class="button is-checked" data-sort-value="original-order">original order</button>
  <button class="button sorter" data-sort-value="name">name</button>
  <button class="button sorter" data-sort-value="symbol">symbol</button>
  <button class="button sorter" data-sort-value="number">number</button>
  <button class="button sorter" data-sort-value="event">events count</button>
  <button class="button sorter" data-sort-value="category">category</button>
</div>

</div>


	
	<div class="event-grid" id="event-grid">
	
		<% @events.each do |event| %>
	
		<%= render(event)%>
		
    <% end %>
  
	
	
	
</div>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Event %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/new.js.erb
	$(".select2").select2({
			theme: "bootstrap", 
		

});
	$(".select_place").select2({
			theme: "bootstrap", 

});
	
	$(".select_day").select2({
			theme: "bootstrap", 

});
vex.open({
	content: '<%= j render("form")%>',
	afterOpen: function($vexContent) {
//		$(".select2").select2({
//			theme: "bootstrap", 
//			tags: true}), 
		$('.vex-last').on('click', function(){
			vex.close();
		});
	}
});

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => Event %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @event.name %></pre></dd>
  </dl>
</div>

<div class="fieldset">
  <dl>
	  <dt class="label label-default"><%= model_class.human_attribute_name(:place) %></dt>
	  <dd><pre class="prettyprint"><% if @event.place%><%= @event.place.name%><%end%>
	  </pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
univers_events_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
edit_univers_event_path(@univers.id, @event), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
univers_event_path(@univers.id, @event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>