config/routes.rb
Rails.application.routes.draw do

  
	root "pages#home"
  	resources :pages
	
	resources :users
	
		resources :universes do
			resources :stories
			resources :days
			resources :events do
				get 'place', on: :member
				resources :places
				end
			resources :chapters
			resources :scenes
			resources :societies
			resources :characters
			resources :artefacts
			resources :places do
				resources :events 
				get 'event', on: :member
				end
			resources :comments
		end
	

	

	
	mount SubdivisionSelect::Engine, at: 'subdivisions'
	
	

  
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/day.rb
class Day < ActiveRecord::Base
	before_save :set_human_day
	belongs_to :univers
	has_many :events
	accepts_nested_attributes_for :events
	validates_uniqueness_of :date,  scope: :univers_id
	validates :date, presence: true
	validates :human_day, presence: true
	
	def set_human_day
	
	end
	
	
	
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
	before_action :require_user_signed_in, only: [:index,:show, :create, :destroy]
	before_action :set_day, only: [:show, :edit, :update, :destroy]
	before_action :set_univers
	before_action :correct_user

 respond_to :html, :js, :xml, :json

  def index
	  
	  @days = @univers.days.all
    
  end

  def show  
	   respond_to do |format|
		format.html { redirect_to univers_days_url, notice: 'Day was successfully destroyed.' }
		format.js #show.js.erb  
     	format.json { head :no_content }
    end
  end

  def new
    @day = @univers.days.build
	  @days = @univers.days
	  
  end

  def edit
  @days = @univers.days
  end

  def create
    
	  @day = @univers.days.build(day_params)
	  
	  @day.human_day = @day.date.strftime("%A %B %d, %Y")
	  @days = @univers.days.order("created_at DESC")
	  respond_to do |format|
   		if @day.save
			format.html { redirect_to univers_places_path, notice: 'Place was successfully created.' }
			format.js #create.js.erb  
			format.json { render :show, status: :created, location: @day }
		else
			format.html { render :new }
			format.json { render json: @day.errors, status: :unprocessable_entity }
		end
	  end
  end

  def update
	  #in model before_save  @day.human_day = @day.date.strftime("%j, %A %B %d, %Y") 
	 respond_to do |format|
		 if @day.update(day_params)
			 format.html { redirect_to univers_days_path, notice: 'Day was successfully updated.' }
		  format.js #update.js.erb  
			 format.json { render :show, status: :ok, location: @day }
      else
        format.html { render :edit }
			 format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @day.destroy
    respond_to do |format|
		format.html { redirect_to univers_days_url, notice: 'Days was successfully destroyed.' }
		format.js #destroy.js.erb  
      format.json { head :no_content }
    end
  end

  private
    def set_day
      @day = Day.find(params[:id])
    end

    def day_params
      params.require(:day).permit(:date, :human_day)
    end
	
	
	
	
	
	def set_univers
		@univers = Univers.find(params[:univers_id])
    end
	
	# Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to root_path
      end
    end
	
	
	
	#check if current user is the creator of the univers
	def correct_user
		unless current_user == @univers.user
			flash[:danger] = "You have no power there"
			redirect_to universes_path
      end
    end
	
	

	
	
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_day.html.erb
<div class="card col3">
lknkjnkjnkj
</div>

app/views/days/_form.html.erb
<%= simple_form_for [@univers, @day], :html => { :class => 'form-horizontal form-model', id: 'new_day_form' }, remote: true do |f| %>

  <div class="field">
	  <%= f.input :date, :start_year=>1700,:end_year=>2100, class: 'select2', id: 'day_field', style:"width: 100%" %>
  </div>

 <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
		<%= f.submit 'make a day', :class => 'vex-dialog-button-primary vex-dialog-button vex-first' %>
		
		<%= link_to 'cancel', '#', :class => 'vex-dialog-button-secondary vex-dialog-button vex-last' %>
    </div>
  </div>
<% end %>

app/views/days/create.js.erb
vex.close();
$('#day_field').html('<%= j collection_select(:event, :day_id, @days, :id, :human_day, {selected: @days.last}, {multiple: false, class: "select_day", id: "day_field"}) %>').trigger('change');

app/views/days/destroy.js.erb
//var $removeItem = $( '#place_<%= @place.id%>' );
//$('.place-grid').isotope( 'remove',  $removeItem ).isotope({ sortBy: 'original-order' });
//$('.place_counter').html();

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/edit.js.erb
vex.open({
	content: '<%= j render("days/_form")%>',
	afterOpen: function($vexContent) {
		$(".select2").select2({
			theme: "bootstrap", 
			tags: true}), 
		$('.vex-last').on('click', function(){
			vex.close();
		})
	}
});
		

app/views/days/index.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.js"></script>
<!-- or -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.2.2/isotope.pkgd.min.js"></script>

<h1>Isotope - sorting</h1>

<div class="button-group sort-by-button-group">
  <button class="button is-checked" data-sort-value="original-order">original order</button>
  <button class="button" data-sort-value="name">name</button>
  <button class="button" data-sort-value="symbol">symbol</button>
  <button class="button" data-sort-value="number">number</button>
  <button class="button" data-sort-value="weight">weight</button>
  <button class="button" data-sort-value="category">category</button>
</div>

<div class="grid">
  
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Mercury</h3>
    <p class="symbol">Hg</p>
    <p class="number">80</p>
    <p class="weight">200.59</p>
  </div>
  
  <div class="element-item metalloid " data-category="metalloid">
    <h3 class="name">Tellurium</h3>
    <p class="symbol">Te</p>
    <p class="number">52</p>
    <p class="weight">127.6</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Bismuth</h3>
    <p class="symbol">Bi</p>
    <p class="number">83</p>
    <p class="weight">208.980</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Lead</h3>
    <p class="symbol">Pb</p>
    <p class="number">82</p>
    <p class="weight">207.2</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Gold</h3>
    <p class="symbol">Au</p>
    <p class="number">79</p>
    <p class="weight">196.967</p>
  </div>
  <div class="element-item alkali metal " data-category="alkali">
    <h3 class="name">Potassium</h3>
    <p class="symbol">K</p>
    <p class="number">19</p>
    <p class="weight">39.0983</p>
  </div>
  <div class="element-item alkali metal " data-category="alkali">
    <h3 class="name">Sodium</h3>
    <p class="symbol">Na</p>
    <p class="number">11</p>
    <p class="weight">22.99</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Cadmium</h3>
    <p class="symbol">Cd</p>
    <p class="number">48</p>
    <p class="weight">112.411</p>
  </div>
  <div class="element-item alkaline-earth metal " data-category="alkaline-earth">
    <h3 class="name">Calcium</h3>
    <p class="symbol">Ca</p>
    <p class="number">20</p>
    <p class="weight">40.078</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Rhenium</h3>
    <p class="symbol">Re</p>
    <p class="number">75</p>
    <p class="weight">186.207</p>
  </div>
  <div class="element-item post-transition metal " data-category="post-transition">
    <h3 class="name">Thallium</h3>
    <p class="symbol">Tl</p>
    <p class="number">81</p>
    <p class="weight">204.383</p>
  </div>
  <div class="element-item metalloid " data-category="metalloid">
    <h3 class="name">Antimony</h3>
    <p class="symbol">Sb</p>
    <p class="number">51</p>
    <p class="weight">121.76</p>
  </div>
  <div class="element-item transition metal " data-category="transition">
    <h3 class="name">Cobalt</h3>
    <p class="symbol">Co</p>
    <p class="number">27</p>
    <p class="weight">58.933</p>
  </div>
  <div class="element-item lanthanoid metal inner-transition " data-category="lanthanoid">
    <h3 class="name">Ytterbium</h3>
    <p class="symbol">Yb</p>
    <p class="number">70</p>
    <p class="weight">173.054</p>
  </div>
  <div class="element-item noble-gas nonmetal " data-category="noble-gas">
    <h3 class="name">Argon</h3>
    <p class="symbol">Ar</p>
    <p class="number">18</p>
    <p class="weight">39.948</p>
  </div>
  <div class="element-item diatomic nonmetal " data-category="diatomic">
    <h3 class="name">Nitrogen</h3>
    <p class="symbol">N</p>
    <p class="number">7</p>
    <p class="weight">14.007</p>
  </div>
  <div class="element-item actinoid metal inner-transition " data-category="actinoid">
    <h3 class="name">Uranium</h3>
    <p class="symbol">U</p>
    <p class="number">92</p>
    <p class="weight">238.029</p>
  </div>
  <div class="element-item actinoid metal inner-transition " data-category="actinoid">
    <h3 class="name">Plutonium</h3>
    <p class="symbol">Pu</p>
    <p class="number">94</p>
    <p class="weight">(244)</p>
  </div>
</div>

app/views/days/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Day %></h1>
</div>
<%= render :partial => 'form' %>

app/views/days/new.js.erb
vex.open({
	content: '<%= j render("form")%>',
	afterOpen: function($vexContent) {
//		$(".select2").select2({
//			theme: "bootstrap", 
//			tags: true}), 
		$('.vex-last').on('click', function(){
			vex.close();
		});
	}
});

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @day.date %>
</p>

<%= link_to 'Edit', edit_univers_day_path(@day) %> |
<%= link_to 'Back', univers_days_path(@univers.id) %>

app/views/days/show.js.erb
vex.open({
	content: '<%= j render(@day)%>',
	afterOpen: function($vexContent) {

		$('.vex-last').on('click', function(){
			vex.close();
		});
	}
});
		

app/views/days/update.js.erb
vex.close();
$('#place_<%=@place.id%>').replaceWith('<%= j render(@place)%>');
$('#place-grid').isotope( 'reloadItems' ).isotope({ sortBy: 'original-order' });