config/routes.rb
Rails.application.routes.draw do

  
	root "pages#home"
  	resources :pages
	
	resources :users
	
		resources :universes do
			resources :stories
			resources :days
			resources :events do
				get 'place', on: :member
				resources :places
				end
			resources :chapters
			resources :scenes
			resources :societies
			resources :characters
			resources :artefacts
			resources :places do
				resources :events 
				get 'event', on: :member
				end
			resources :comments
		end
	

	

	
	mount SubdivisionSelect::Engine, at: 'subdivisions'
	
	

  
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
	belongs_to :univers
	default_scope -> { order(created_at: :desc) }
	validates :univers_id, presence: true
	validates :name, presence: true, length: { maximum: 140 }
	
	has_many :events
	accepts_nested_attributes_for :events
	
	validates_uniqueness_of :name, scope: :univers_id
	
		#for the text_method in forms
		def place_city_country
				"#{name} in #{city}, #{country}"
  		end
	
	def country_name
		if ISO3166::Country[country]
		the_country = ISO3166::Country[country]
		the_country.translations[I18n.locale.to_s] || country.name
		end
  	end
	
	
	
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :require_user_signed_in, only: [:index,:show, :create, :destroy]
	before_action :set_place, only: [:show, :edit, :update, :destroy]
	before_action :set_univers
	before_action :correct_user
	before_action :pull_countries, only: [:new, :edit, :index]
	
	
	respond_to :html, :js, :xml, :json

  # GET /places
  # GET /places.json
  def index
	  @places = @univers.places
  end

  # GET /places/1
  # GET /places/1.json
  def show
	   respond_to do |format|
		format.html { redirect_to univers_places_url, notice: 'Place was successfully destroyed.' }
		format.js #show.js.erb  
      format.json { head :no_content }
    end
  end


	
  # GET /places/new
  def new
	  @place = @univers.places.build
	  
	  
  end

	def pull_countries #pull used country in specific univers
		@newarray = Array.new
		@cities = Array.new
		@country_name_array = Array.new
		places = @univers.places.all
		places.each do |place|
			@newarray << place.country
			@country_name_array << place.country_name
			@cities << place.city 
		end
	
		
		@top_countries =  @newarray.uniq
		@top_countries_name = @country_name_array.uniq
		@cities = @cities.compact.uniq
	end
	
	

	
	
	

  # GET /places/1/edit
  def edit
	   
	  
  end

  # POST /places
  # POST /places.json
  def create
	  @place = @univers.places.build(place_params)
	  @places = @univers.places.all

    respond_to do |format|
      if @place.save
		format.html { redirect_to univers_places_path, notice: 'Place was successfully created.' }
		format.js #create.js.erb  
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
		  format.html { redirect_to univers_places_path, notice: 'Place was successfully updated.' }
		  format.js #update.js.erb  
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
		format.html { redirect_to univers_places_url, notice: 'Place was successfully destroyed.' }
		format.js #destroy.js.erb  
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name,:city, :country, :subdivision, :latitude, :longitude)
    end
	
	
	
	def set_univers
		@univers = Univers.find(params[:univers_id])
    end
	
	# Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to root_path
      end
    end
	
	
	
	#check if current user is the creator of the univers
	def correct_user
		unless current_user == @univers.user
			flash[:danger] = "You have no power there"
			redirect_to universes_path
      end
    end
	
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for [@univers,@place], :html => { :class => 'form-horizontal form-model', id: 'new_place_form' }, remote: true do |f| %>


  <div class="field">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
		<%= f.text_field :name, :class => 'text-field form-control', autofocus:true %>
    </div>
  </div>


 

 <div class="field">
    <%= f.label :city %>

	 <%= select(:place, :city, @cities,{}, {class: "select2", style:"width: 50%", style:"width: 100%"}) %>
	 
  </div>  


<div class="field">
    <%= f.label :country %>
	<%= country_select(:place, :country, {priority_countries:  @top_countries.reverse},  {class: "select2", style:"width: 100%"}) %>
  </div>


  <div class="field">
    <%= f.label :subdivision, "State / Province" %>
	  <%= f.subdivision_select :subdivision, :country,  {prompt: 'Please select a country..'}, {class: "select2", style:"width: 100%"}  %>
  </div>




  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :latitude, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :longitude, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'vex-dialog-button-primary vex-dialog-button vex-first' %>
		
		<%= link_to 'cancel', '#', :class => 'vex-dialog-button-secondary vex-dialog-button vex-last' %>
    </div>
  </div>

<% end %>

app/views/places/_place.html.erb
<%= link_to univers_place_path(@univers, place.id), remote: true do %>
  
		<%if place.country_name.nil?%>
	
<div class="card col3 nocountry" id="<%= 'place_'+place.id.to_s%>" data-category="">
			
			<%else%>
			<div class="card col3 <%= place.country_name.delete(' '+','+"'"+"("+")"+".")%>", id="<%= 'place_'+place.id.to_s%>" data-category="">
			<%end%>
			
		<div class="top-box">
			<b class="name"> <%= place.name %> </b>
			<div class="event">
				<% if place.events.count == 0 %> 
				<div class="invisible"> <%= place.events.count%></div>
				<%else%>
					<%= place.events.count%>
				<% end%>
		</div>
			</div>
		<div class="middle-box">
		in 
			<%= unless place.city.blank?
            "#{place.city}," end%>
			
			<%= place.country_name%>
			
			
		</div>
	
		<div class="bottom-box">		
			<%= link_to "EDIT", edit_univers_place_path(@univers.id, place),remote: true%>
			<%= link_to "remove", univers_place_path(@univers.id,place), :method => :delete,remote: true, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs' %>
			</div>
</div>
		<% end %>

app/views/places/create.js.erb
vex.close();
alert("I am an alert box!");
$('#place-grid').prepend('<%= j render(@place)%>').isotope( 'reloadItems' ).isotope({ sortBy: 'original-order' });
//$('#placefield').html('<%= j render partial: "events/place_fields", object: @places %>');
$('#place_field').html('<%= j collection_select(:event, :place_id, @places, :id, :name, {selected: @places.last}, {multiple: false, class: "select_place", id: "place_field"}) %>').trigger('change');

app/views/places/destroy.js.erb
var $removeItem = $( '#place_<%= @place.id%>' );
$('.place-grid').isotope( 'remove',  $removeItem ).isotope({ sortBy: 'original-order' });
$('.place_counter').html();

app/views/places/edit.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Place %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/edit.js.erb
vex.open({
	content: '<%= j render("form")%>',
	afterOpen: function($vexContent) {
		$(".select2").select2({
			theme: "bootstrap", 
			tags: true}), 
		$('.vex-last').on('click', function(){
			vex.close();
		})
	}
});
		

app/views/places/index.html.erb
<div class="filters_nav">
	<%= link_to "New Place", new_univers_place_path, id: 'new_place_link',remote: true %> <br/>
	<%= link_to 'New Day', new_univers_day_path,id: 'new_day_link', remote: true%>


	
filtering Countries
<div class="button-group filters-button-group">
	 <button class="button is-checked" data-filter="*">show all</button>
	<% @top_countries_name.each do |c| %>
	
	
	<% if c.nil?%>
	
	<button class="button" data-filter=".nocountry"> no country</button>
	
	<%else%>
	<button class="button" data-filter=".<%= c.delete(' '+','+"'"+"("+")"+".")%>"> <%= c%></button>
	<%end%>
	
	
<%end%>
</div>
Sorting Countries

 <div class="button-group sort-place-by-button-group">
  <button class="button is-checked" data-sort-value="original-order">original order</button>
  <button class="button sorter" data-sort-value="name">name</button>
  <button class="button sorter" data-sort-value="symbol">symbol</button>
  <button class="button sorter" data-sort-value="number">number</button>
  <button class="button sorter" data-sort-value="event">events count</button>
  <button class="button sorter" data-sort-value="category">category</button>
</div>

</div>


	
	<div class="place-grid" id="place-grid">
	
    <% @places.each do |place| %>
	
		<%= render(place)%>
		
    <% end %>
  
	
	
	
</div>

app/views/places/new.html.erb
<%- model_class = Place -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Place %></h1>
</div>
<%= render :partial => 'form' %>

app/views/places/new.js.erb
$('#new_place_link').hide().after('<%= j render("form")%>');
$( ".select2" ).select2({
    theme: "bootstrap",	
	 tags: true
	
});

app/views/places/search.js.erb
  var qsRegex;
  
  // init Isotope
  var $grid = $('.grid').isotope({
    itemSelector: '.card',
    layoutMode: 'masonry',
    filter: function() {
      return qsRegex ? $(this).text().match( qsRegex ) : true;
    }
  });

  // use value of search field to filter
  var $quicksearch = $('.quicksearch').keyup( debounce( function() {
    qsRegex = new RegExp( $quicksearch.val(), 'gi' );
    $grid.isotope();
  }, 200 ) );
  
});

// debounce so filtering doesn't happen every millisecond
function debounce( fn, threshold ) {
  var timeout;
  return function debounced() {
    if ( timeout ) {
      clearTimeout( timeout );
    }
    function delayed() {
      fn();
      timeout = null;
    }
    timeout = setTimeout( delayed, threshold || 100 );
  }
}

app/views/places/show.html.erb
<%- model_class = Place -%>


<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @place.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:latitude) %></dt>
      <dd><pre class="prettyprint"><%= @place.latitude %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:longitude) %></dt>
      <dd><pre class="prettyprint"><%= @place.longitude %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
univers_places_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
edit_univers_place_path(@univers.id,@place), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
univers_place_path(@univers.id,@place),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<ul>
<% @place.events.each do |event|%>

	<li>
<b><%= event.name %> </b>
		| <b><% if event.day %><%= event.day.human_day%>  <%else%> <%=  link_to "no date", edit_univers_event_path(@univers.id, event.id) %> <%end%></b>
		| <b>character here </b>
</li>

<%end%>
</ul>

app/views/places/show.js.erb
vex.open({
	content: '<%= j render(@place)%>',
	afterOpen: function($vexContent) {

		$('.vex-last').on('click', function(){
			vex.close();
		});
	}
});
		